### ISSUE TITLE
Loop so no need to rerun. 

### ISSUE THREAD

**Issue by JayUpadhyayCS** [guardians-of-the-code/Calculator#2]
Need a way to loop the program to run until the user wants it to end. Maybe a bool loop that gets triggered to by something of user input?

**Comment by Daniel-Stahl** [comment]
I got this!

**Comment by JayUpadhyayCS** [comment]
Functional and working! Maybe at some point in the future have it automatically take input(END or operation) and either end or run the operation depending on which it gets. I'll leave this open for that reason.

**Comment by JayUpadhyayCS** [comment]
Done. Takes input or ends upon taking q/Q.
